### ISSUE TITLE
Still sends the escape through to the host?

### ISSUE THREAD

**Issue by glasser** [keyboardio/Kaleidoscope-Escape-OneShot#3]
At least on my system it still seems to type the escape. Not sure why. Maybe because we only handle the key down and not the key up?

**Comment by algernon** [comment]
Possibly, yes. I only started noticing this recently too (but it could have been this way forever, just without me noticing), but didn't have time to dig deeper yet. Only handling the key press might be the reason.

**Comment by algernon** [comment]
Fixed by #4.

The problem was that the code was a little too eager. You see, when tapping a key, a single tap usually takes longer than a single cycle for the keyboard firmware. In the first cycle, the plugin saw that OneShot was active, cancelled it, and did not send any other key. Come the next cycle, the key is still held! But OneShot is not active anymore, so Esc is let through.

The fix was to mask the Esc key until it is released, so any extra holds won't accidentally send Esc through.
